/** ATS city → state mapping. Keys are the snake_case city IDs from game.sii. */
export const ATS_CITIES: Record<string, { name: string; state: string; abbr: string }> = {
  // Arizona
  flagstaff: { name: "Flagstaff", state: "Arizona", abbr: "AZ" },
  holbrook: { name: "Holbrook", state: "Arizona", abbr: "AZ" },
  kayenta: { name: "Kayenta", state: "Arizona", abbr: "AZ" },
  kingman: { name: "Kingman", state: "Arizona", abbr: "AZ" },
  nogales: { name: "Nogales", state: "Arizona", abbr: "AZ" },
  page: { name: "Page", state: "Arizona", abbr: "AZ" },
  phoenix: { name: "Phoenix", state: "Arizona", abbr: "AZ" },
  prescott: { name: "Prescott", state: "Arizona", abbr: "AZ" },
  show_low: { name: "Show Low", state: "Arizona", abbr: "AZ" },
  sierra_vista: { name: "Sierra Vista", state: "Arizona", abbr: "AZ" },
  tucson: { name: "Tucson", state: "Arizona", abbr: "AZ" },
  yuma: { name: "Yuma", state: "Arizona", abbr: "AZ" },
  // Arkansas
  el_dorado: { name: "El Dorado", state: "Arkansas", abbr: "AR" },
  fort_smith: { name: "Fort Smith", state: "Arkansas", abbr: "AR" },
  harrison: { name: "Harrison", state: "Arkansas", abbr: "AR" },
  hot_springs: { name: "Hot Springs", state: "Arkansas", abbr: "AR" },
  jonesboro: { name: "Jonesboro", state: "Arkansas", abbr: "AR" },
  little_rock: { name: "Little Rock", state: "Arkansas", abbr: "AR" },
  pine_bluff: { name: "Pine Bluff", state: "Arkansas", abbr: "AR" },
  springdale: { name: "Springdale", state: "Arkansas", abbr: "AR" },
  texarkana_ar: { name: "Texarkana", state: "Arkansas", abbr: "AR" },
  // California
  bakersfield: { name: "Bakersfield", state: "California", abbr: "CA" },
  barstow: { name: "Barstow", state: "California", abbr: "CA" },
  el_centro: { name: "El Centro", state: "California", abbr: "CA" },
  eureka: { name: "Eureka", state: "California", abbr: "CA" },
  fresno: { name: "Fresno", state: "California", abbr: "CA" },
  huron: { name: "Huron", state: "California", abbr: "CA" },
  indio: { name: "Indio", state: "California", abbr: "CA" },
  los_angeles: { name: "Los Angeles", state: "California", abbr: "CA" },
  oakland: { name: "Oakland", state: "California", abbr: "CA" },
  oxnard: { name: "Oxnard", state: "California", abbr: "CA" },
  redding: { name: "Redding", state: "California", abbr: "CA" },
  sacramento: { name: "Sacramento", state: "California", abbr: "CA" },
  san_diego: { name: "San Diego", state: "California", abbr: "CA" },
  san_francisco: { name: "San Francisco", state: "California", abbr: "CA" },
  san_rafael: { name: "San Rafael", state: "California", abbr: "CA" },
  santa_cruz: { name: "Santa Cruz", state: "California", abbr: "CA" },
  santa_maria: { name: "Santa Maria", state: "California", abbr: "CA" },
  stockton: { name: "Stockton", state: "California", abbr: "CA" },
  truckee: { name: "Truckee", state: "California", abbr: "CA" },
  ukiah: { name: "Ukiah", state: "California", abbr: "CA" },
  // Colorado
  boulder: { name: "Boulder", state: "Colorado", abbr: "CO" },
  colorado_springs: { name: "Colorado Springs", state: "Colorado", abbr: "CO" },
  craig: { name: "Craig", state: "Colorado", abbr: "CO" },
  denver: { name: "Denver", state: "Colorado", abbr: "CO" },
  durango: { name: "Durango", state: "Colorado", abbr: "CO" },
  fort_collins: { name: "Fort Collins", state: "Colorado", abbr: "CO" },
  grand_junction: { name: "Grand Junction", state: "Colorado", abbr: "CO" },
  pueblo: { name: "Pueblo", state: "Colorado", abbr: "CO" },
  trinidad: { name: "Trinidad", state: "Colorado", abbr: "CO" },
  // Idaho
  boise: { name: "Boise", state: "Idaho", abbr: "ID" },
  coeur_d_alene: { name: "Coeur d'Alene", state: "Idaho", abbr: "ID" },
  idaho_falls: { name: "Idaho Falls", state: "Idaho", abbr: "ID" },
  lewiston: { name: "Lewiston", state: "Idaho", abbr: "ID" },
  pocatello: { name: "Pocatello", state: "Idaho", abbr: "ID" },
  twin_falls: { name: "Twin Falls", state: "Idaho", abbr: "ID" },
  // Iowa
  cedar_rapids: { name: "Cedar Rapids", state: "Iowa", abbr: "IA" },
  council_bluffs: { name: "Council Bluffs", state: "Iowa", abbr: "IA" },
  des_moines: { name: "Des Moines", state: "Iowa", abbr: "IA" },
  dubuque: { name: "Dubuque", state: "Iowa", abbr: "IA" },
  iowa_city: { name: "Iowa City", state: "Iowa", abbr: "IA" },
  sioux_city: { name: "Sioux City", state: "Iowa", abbr: "IA" },
  // Kansas
  dodge_city: { name: "Dodge City", state: "Kansas", abbr: "KS" },
  garden_city: { name: "Garden City", state: "Kansas", abbr: "KS" },
  hays: { name: "Hays", state: "Kansas", abbr: "KS" },
  kansas_city_ks: { name: "Kansas City", state: "Kansas", abbr: "KS" },
  liberal: { name: "Liberal", state: "Kansas", abbr: "KS" },
  salina: { name: "Salina", state: "Kansas", abbr: "KS" },
  topeka: { name: "Topeka", state: "Kansas", abbr: "KS" },
  wichita: { name: "Wichita", state: "Kansas", abbr: "KS" },
  // Montana
  billings: { name: "Billings", state: "Montana", abbr: "MT" },
  butte: { name: "Butte", state: "Montana", abbr: "MT" },
  great_falls: { name: "Great Falls", state: "Montana", abbr: "MT" },
  havre: { name: "Havre", state: "Montana", abbr: "MT" },
  helena: { name: "Helena", state: "Montana", abbr: "MT" },
  kalispell: { name: "Kalispell", state: "Montana", abbr: "MT" },
  miles_city: { name: "Miles City", state: "Montana", abbr: "MT" },
  missoula: { name: "Missoula", state: "Montana", abbr: "MT" },
  // Nebraska
  grand_island: { name: "Grand Island", state: "Nebraska", abbr: "NE" },
  kearney: { name: "Kearney", state: "Nebraska", abbr: "NE" },
  lincoln: { name: "Lincoln", state: "Nebraska", abbr: "NE" },
  north_platte: { name: "North Platte", state: "Nebraska", abbr: "NE" },
  norfolk: { name: "Norfolk", state: "Nebraska", abbr: "NE" },
  omaha: { name: "Omaha", state: "Nebraska", abbr: "NE" },
  scottsbluff: { name: "Scottsbluff", state: "Nebraska", abbr: "NE" },
  // Nevada
  carson_city: { name: "Carson City", state: "Nevada", abbr: "NV" },
  elko: { name: "Elko", state: "Nevada", abbr: "NV" },
  ely: { name: "Ely", state: "Nevada", abbr: "NV" },
  las_vegas: { name: "Las Vegas", state: "Nevada", abbr: "NV" },
  pioche: { name: "Pioche", state: "Nevada", abbr: "NV" },
  reno: { name: "Reno", state: "Nevada", abbr: "NV" },
  tonopah: { name: "Tonopah", state: "Nevada", abbr: "NV" },
  winnemucca: { name: "Winnemucca", state: "Nevada", abbr: "NV" },
  // New Mexico
  albuquerque: { name: "Albuquerque", state: "New Mexico", abbr: "NM" },
  carlsbad: { name: "Carlsbad", state: "New Mexico", abbr: "NM" },
  clovis: { name: "Clovis", state: "New Mexico", abbr: "NM" },
  farmington: { name: "Farmington", state: "New Mexico", abbr: "NM" },
  gallup: { name: "Gallup", state: "New Mexico", abbr: "NM" },
  las_cruces: { name: "Las Cruces", state: "New Mexico", abbr: "NM" },
  roswell: { name: "Roswell", state: "New Mexico", abbr: "NM" },
  santa_fe: { name: "Santa Fe", state: "New Mexico", abbr: "NM" },
  socorro: { name: "Socorro", state: "New Mexico", abbr: "NM" },
  tucumcari: { name: "Tucumcari", state: "New Mexico", abbr: "NM" },
  // Oklahoma
  amarillo: { name: "Amarillo", state: "Oklahoma", abbr: "OK" },
  enid: { name: "Enid", state: "Oklahoma", abbr: "OK" },
  lawton: { name: "Lawton", state: "Oklahoma", abbr: "OK" },
  oklahoma_city: { name: "Oklahoma City", state: "Oklahoma", abbr: "OK" },
  tulsa: { name: "Tulsa", state: "Oklahoma", abbr: "OK" },
  woodward: { name: "Woodward", state: "Oklahoma", abbr: "OK" },
  // Oregon
  astoria: { name: "Astoria", state: "Oregon", abbr: "OR" },
  bend: { name: "Bend", state: "Oregon", abbr: "OR" },
  burns: { name: "Burns", state: "Oregon", abbr: "OR" },
  coos_bay: { name: "Coos Bay", state: "Oregon", abbr: "OR" },
  eugene: { name: "Eugene", state: "Oregon", abbr: "OR" },
  klamath_falls: { name: "Klamath Falls", state: "Oregon", abbr: "OR" },
  medford: { name: "Medford", state: "Oregon", abbr: "OR" },
  newport: { name: "Newport", state: "Oregon", abbr: "OR" },
  ontario: { name: "Ontario", state: "Oregon", abbr: "OR" },
  pendleton: { name: "Pendleton", state: "Oregon", abbr: "OR" },
  portland: { name: "Portland", state: "Oregon", abbr: "OR" },
  salem: { name: "Salem", state: "Oregon", abbr: "OR" },
  the_dalles: { name: "The Dalles", state: "Oregon", abbr: "OR" },
  // Texas
  amarillo_tx: { name: "Amarillo", state: "Texas", abbr: "TX" },
  dallas: { name: "Dallas", state: "Texas", abbr: "TX" },
  el_paso: { name: "El Paso", state: "Texas", abbr: "TX" },
  houston: { name: "Houston", state: "Texas", abbr: "TX" },
  lubbock: { name: "Lubbock", state: "Texas", abbr: "TX" },
  odessa: { name: "Odessa", state: "Texas", abbr: "TX" },
  san_antonio: { name: "San Antonio", state: "Texas", abbr: "TX" },
  // Utah
  cedar_city: { name: "Cedar City", state: "Utah", abbr: "UT" },
  logan: { name: "Logan", state: "Utah", abbr: "UT" },
  ogden: { name: "Ogden", state: "Utah", abbr: "UT" },
  price: { name: "Price", state: "Utah", abbr: "UT" },
  provo: { name: "Provo", state: "Utah", abbr: "UT" },
  salt_lake_city: { name: "Salt Lake City", state: "Utah", abbr: "UT" },
  st_george: { name: "St. George", state: "Utah", abbr: "UT" },
  vernal: { name: "Vernal", state: "Utah", abbr: "UT" },
  // Washington
  bellingham: { name: "Bellingham", state: "Washington", abbr: "WA" },
  ellensburg: { name: "Ellensburg", state: "Washington", abbr: "WA" },
  everett: { name: "Everett", state: "Washington", abbr: "WA" },
  grand_coulee: { name: "Grand Coulee", state: "Washington", abbr: "WA" },
  kennewick: { name: "Kennewick", state: "Washington", abbr: "WA" },
  longview: { name: "Longview", state: "Washington", abbr: "WA" },
  olympia: { name: "Olympia", state: "Washington", abbr: "WA" },
  port_angeles: { name: "Port Angeles", state: "Washington", abbr: "WA" },
  seattle: { name: "Seattle", state: "Washington", abbr: "WA" },
  spokane: { name: "Spokane", state: "Washington", abbr: "WA" },
  tacoma: { name: "Tacoma", state: "Washington", abbr: "WA" },
  vancouver_wa: { name: "Vancouver", state: "Washington", abbr: "WA" },
  yakima: { name: "Yakima", state: "Washington", abbr: "WA" },
  // Wyoming
  casper: { name: "Casper", state: "Wyoming", abbr: "WY" },
  cheyenne: { name: "Cheyenne", state: "Wyoming", abbr: "WY" },
  cody: { name: "Cody", state: "Wyoming", abbr: "WY" },
  evanston: { name: "Evanston", state: "Wyoming", abbr: "WY" },
  gillette: { name: "Gillette", state: "Wyoming", abbr: "WY" },
  jackson: { name: "Jackson", state: "Wyoming", abbr: "WY" },
  rawlins: { name: "Rawlins", state: "Wyoming", abbr: "WY" },
  rock_springs: { name: "Rock Springs", state: "Wyoming", abbr: "WY" },
  sheridan: { name: "Sheridan", state: "Wyoming", abbr: "WY" },
};

/** Look up state info for a city. Falls back to "Unknown" for unmapped cities. */
export function getCityInfo(cityId: string): { name: string; state: string; abbr: string } {
  return (
    ATS_CITIES[cityId] ?? {
      name: cityId.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      state: "Unknown",
      abbr: "??",
    }
  );
}

/** All unique state abbreviations, sorted. */
export const ATS_STATES = [
  ...new Set(Object.values(ATS_CITIES).map((c) => c.abbr)),
].sort();
