/** ATS city → state mapping. Keys are the snake_case city IDs from game.sii. */
export const ATS_CITIES: Record<string, { name: string; state: string; abbr: string }> = {
  // Arizona
  camp_verde: { name: "Camp Verde", state: "Arizona", abbr: "AZ" },
  clifton: { name: "Clifton", state: "Arizona", abbr: "AZ" },
  flagstaff: { name: "Flagstaff", state: "Arizona", abbr: "AZ" },
  grand_canyon_village: { name: "Grand Canyon Village", state: "Arizona", abbr: "AZ" },
  holbrook: { name: "Holbrook", state: "Arizona", abbr: "AZ" },
  kayenta: { name: "Kayenta", state: "Arizona", abbr: "AZ" },
  kingman: { name: "Kingman", state: "Arizona", abbr: "AZ" },
  lake_havasu_city: { name: "Lake Havasu City", state: "Arizona", abbr: "AZ" },
  nogales: { name: "Nogales", state: "Arizona", abbr: "AZ" },
  page: { name: "Page", state: "Arizona", abbr: "AZ" },
  phoenix: { name: "Phoenix", state: "Arizona", abbr: "AZ" },
  prescott: { name: "Prescott", state: "Arizona", abbr: "AZ" },
  san_simon: { name: "San Simon", state: "Arizona", abbr: "AZ" },
  show_low: { name: "Show Low", state: "Arizona", abbr: "AZ" },
  sierra_vista: { name: "Sierra Vista", state: "Arizona", abbr: "AZ" },
  tucson: { name: "Tucson", state: "Arizona", abbr: "AZ" },
  winslow: { name: "Winslow", state: "Arizona", abbr: "AZ" },
  yuma: { name: "Yuma", state: "Arizona", abbr: "AZ" },
  // Arkansas
  el_dorado: { name: "El Dorado", state: "Arkansas", abbr: "AR" },
  fayetteville: { name: "Fayetteville", state: "Arkansas", abbr: "AR" },
  fort_smith: { name: "Fort Smith", state: "Arkansas", abbr: "AR" },
  harrison: { name: "Harrison", state: "Arkansas", abbr: "AR" },
  hot_springs: { name: "Hot Springs", state: "Arkansas", abbr: "AR" },
  jonesboro: { name: "Jonesboro", state: "Arkansas", abbr: "AR" },
  little_rock: { name: "Little Rock", state: "Arkansas", abbr: "AR" },
  pine_bluff: { name: "Pine Bluff", state: "Arkansas", abbr: "AR" },
  springdale: { name: "Springdale", state: "Arkansas", abbr: "AR" },
  texarkana_ar: { name: "Texarkana", state: "Arkansas", abbr: "AR" },
  // California
  bakersfield: { name: "Bakersfield", state: "California", abbr: "CA" },
  barstow: { name: "Barstow", state: "California", abbr: "CA" },
  blythe: { name: "Blythe", state: "California", abbr: "CA" },
  el_centro: { name: "El Centro", state: "California", abbr: "CA" },
  eureka: { name: "Eureka", state: "California", abbr: "CA" },
  fresno: { name: "Fresno", state: "California", abbr: "CA" },
  hilt: { name: "Hilt", state: "California", abbr: "CA" },
  huron: { name: "Huron", state: "California", abbr: "CA" },
  indio: { name: "Indio", state: "California", abbr: "CA" },
  los_angeles: { name: "Los Angeles", state: "California", abbr: "CA" },
  modesto: { name: "Modesto", state: "California", abbr: "CA" },
  mojave: { name: "Mojave", state: "California", abbr: "CA" },
  oakland: { name: "Oakland", state: "California", abbr: "CA" },
  oxnard: { name: "Oxnard", state: "California", abbr: "CA" },
  redding: { name: "Redding", state: "California", abbr: "CA" },
  sacramento: { name: "Sacramento", state: "California", abbr: "CA" },
  san_diego: { name: "San Diego", state: "California", abbr: "CA" },
  san_francisco: { name: "San Francisco", state: "California", abbr: "CA" },
  san_jose: { name: "San Jose", state: "California", abbr: "CA" },
  san_rafael: { name: "San Rafael", state: "California", abbr: "CA" },
  santa_cruz: { name: "Santa Cruz", state: "California", abbr: "CA" },
  santa_maria: { name: "Santa Maria", state: "California", abbr: "CA" },
  stockton: { name: "Stockton", state: "California", abbr: "CA" },
  truckee: { name: "Truckee", state: "California", abbr: "CA" },
  ukiah: { name: "Ukiah", state: "California", abbr: "CA" },
  // Colorado
  alamosa: { name: "Alamosa", state: "Colorado", abbr: "CO" },
  boulder: { name: "Boulder", state: "Colorado", abbr: "CO" },
  burlington_co: { name: "Burlington", state: "Colorado", abbr: "CO" },
  colorado_springs: { name: "Colorado Springs", state: "Colorado", abbr: "CO" },
  craig: { name: "Craig", state: "Colorado", abbr: "CO" },
  denver: { name: "Denver", state: "Colorado", abbr: "CO" },
  durango: { name: "Durango", state: "Colorado", abbr: "CO" },
  fort_collins: { name: "Fort Collins", state: "Colorado", abbr: "CO" },
  grand_junction: { name: "Grand Junction", state: "Colorado", abbr: "CO" },
  lamar: { name: "Lamar", state: "Colorado", abbr: "CO" },
  montrose: { name: "Montrose", state: "Colorado", abbr: "CO" },
  pueblo: { name: "Pueblo", state: "Colorado", abbr: "CO" },
  rangely: { name: "Rangely", state: "Colorado", abbr: "CO" },
  steamboat_springs: { name: "Steamboat Springs", state: "Colorado", abbr: "CO" },
  sterling: { name: "Sterling", state: "Colorado", abbr: "CO" },
  trinidad: { name: "Trinidad", state: "Colorado", abbr: "CO" },
  // Idaho
  boise: { name: "Boise", state: "Idaho", abbr: "ID" },
  coeur_d_alene: { name: "Coeur d'Alene", state: "Idaho", abbr: "ID" },
  grangeville: { name: "Grangeville", state: "Idaho", abbr: "ID" },
  idaho_falls: { name: "Idaho Falls", state: "Idaho", abbr: "ID" },
  ketchum: { name: "Ketchum", state: "Idaho", abbr: "ID" },
  lewiston: { name: "Lewiston", state: "Idaho", abbr: "ID" },
  nampa: { name: "Nampa", state: "Idaho", abbr: "ID" },
  pocatello: { name: "Pocatello", state: "Idaho", abbr: "ID" },
  salmon: { name: "Salmon", state: "Idaho", abbr: "ID" },
  sandpoint: { name: "Sandpoint", state: "Idaho", abbr: "ID" },
  twin_falls: { name: "Twin Falls", state: "Idaho", abbr: "ID" },
  // Iowa
  burlington_ia: { name: "Burlington", state: "Iowa", abbr: "IA" },
  cedar_rapids: { name: "Cedar Rapids", state: "Iowa", abbr: "IA" },
  council_bluffs: { name: "Council Bluffs", state: "Iowa", abbr: "IA" },
  davenport: { name: "Davenport", state: "Iowa", abbr: "IA" },
  des_moines: { name: "Des Moines", state: "Iowa", abbr: "IA" },
  dubuque: { name: "Dubuque", state: "Iowa", abbr: "IA" },
  fort_dodge: { name: "Fort Dodge", state: "Iowa", abbr: "IA" },
  iowa_city: { name: "Iowa City", state: "Iowa", abbr: "IA" },
  mason_city: { name: "Mason City", state: "Iowa", abbr: "IA" },
  ottumwa: { name: "Ottumwa", state: "Iowa", abbr: "IA" },
  sioux_city: { name: "Sioux City", state: "Iowa", abbr: "IA" },
  waterloo: { name: "Waterloo", state: "Iowa", abbr: "IA" },
  // Kansas
  colby: { name: "Colby", state: "Kansas", abbr: "KS" },
  dodge_city: { name: "Dodge City", state: "Kansas", abbr: "KS" },
  emporia: { name: "Emporia", state: "Kansas", abbr: "KS" },
  garden_city: { name: "Garden City", state: "Kansas", abbr: "KS" },
  hays: { name: "Hays", state: "Kansas", abbr: "KS" },
  hutchinson: { name: "Hutchinson", state: "Kansas", abbr: "KS" },
  junction_city: { name: "Junction City", state: "Kansas", abbr: "KS" },
  kansas_city_ks: { name: "Kansas City", state: "Kansas", abbr: "KS" },
  liberal: { name: "Liberal", state: "Kansas", abbr: "KS" },
  marysville: { name: "Marysville", state: "Kansas", abbr: "KS" },
  phillipsburg: { name: "Phillipsburg", state: "Kansas", abbr: "KS" },
  pittsburg: { name: "Pittsburg", state: "Kansas", abbr: "KS" },
  salina: { name: "Salina", state: "Kansas", abbr: "KS" },
  topeka: { name: "Topeka", state: "Kansas", abbr: "KS" },
  wichita: { name: "Wichita", state: "Kansas", abbr: "KS" },
  // Louisiana
  alexandria: { name: "Alexandria", state: "Louisiana", abbr: "LA" },
  baton_rouge: { name: "Baton Rouge", state: "Louisiana", abbr: "LA" },
  deridder: { name: "DeRidder", state: "Louisiana", abbr: "LA" },
  houma: { name: "Houma", state: "Louisiana", abbr: "LA" },
  lafayette: { name: "Lafayette", state: "Louisiana", abbr: "LA" },
  lake_charles: { name: "Lake Charles", state: "Louisiana", abbr: "LA" },
  monroe_la: { name: "Monroe", state: "Louisiana", abbr: "LA" },
  natchitoches: { name: "Natchitoches", state: "Louisiana", abbr: "LA" },
  new_orleans: { name: "New Orleans", state: "Louisiana", abbr: "LA" },
  port_fourchon: { name: "Port Fourchon", state: "Louisiana", abbr: "LA" },
  shreveport: { name: "Shreveport", state: "Louisiana", abbr: "LA" },
  // Missouri
  cape_girardeau: { name: "Cape Girardeau", state: "Missouri", abbr: "MO" },
  columbia_mo: { name: "Columbia", state: "Missouri", abbr: "MO" },
  jefferson_city: { name: "Jefferson City", state: "Missouri", abbr: "MO" },
  joplin: { name: "Joplin", state: "Missouri", abbr: "MO" },
  kansas_city_mo: { name: "Kansas City", state: "Missouri", abbr: "MO" },
  kirksville: { name: "Kirksville", state: "Missouri", abbr: "MO" },
  maryville_mo: { name: "Maryville", state: "Missouri", abbr: "MO" },
  poplar_bluff: { name: "Poplar Bluff", state: "Missouri", abbr: "MO" },
  rolla: { name: "Rolla", state: "Missouri", abbr: "MO" },
  springfield_mo: { name: "Springfield", state: "Missouri", abbr: "MO" },
  st_joseph: { name: "St. Joseph", state: "Missouri", abbr: "MO" },
  st_louis: { name: "St. Louis", state: "Missouri", abbr: "MO" },
  // Montana
  billings: { name: "Billings", state: "Montana", abbr: "MT" },
  bozeman: { name: "Bozeman", state: "Montana", abbr: "MT" },
  butte: { name: "Butte", state: "Montana", abbr: "MT" },
  glasgow: { name: "Glasgow", state: "Montana", abbr: "MT" },
  glendive: { name: "Glendive", state: "Montana", abbr: "MT" },
  great_falls: { name: "Great Falls", state: "Montana", abbr: "MT" },
  havre: { name: "Havre", state: "Montana", abbr: "MT" },
  helena: { name: "Helena", state: "Montana", abbr: "MT" },
  kalispell: { name: "Kalispell", state: "Montana", abbr: "MT" },
  laurel: { name: "Laurel", state: "Montana", abbr: "MT" },
  lewistown: { name: "Lewistown", state: "Montana", abbr: "MT" },
  miles_city: { name: "Miles City", state: "Montana", abbr: "MT" },
  missoula: { name: "Missoula", state: "Montana", abbr: "MT" },
  sidney_mt: { name: "Sidney", state: "Montana", abbr: "MT" },
  thompson_falls: { name: "Thompson Falls", state: "Montana", abbr: "MT" },
  // Nebraska
  alliance: { name: "Alliance", state: "Nebraska", abbr: "NE" },
  chadron: { name: "Chadron", state: "Nebraska", abbr: "NE" },
  columbus_ne: { name: "Columbus", state: "Nebraska", abbr: "NE" },
  grand_island: { name: "Grand Island", state: "Nebraska", abbr: "NE" },
  kearney: { name: "Kearney", state: "Nebraska", abbr: "NE" },
  lincoln: { name: "Lincoln", state: "Nebraska", abbr: "NE" },
  mccook: { name: "McCook", state: "Nebraska", abbr: "NE" },
  norfolk: { name: "Norfolk", state: "Nebraska", abbr: "NE" },
  north_platte: { name: "North Platte", state: "Nebraska", abbr: "NE" },
  omaha: { name: "Omaha", state: "Nebraska", abbr: "NE" },
  scottsbluff: { name: "Scottsbluff", state: "Nebraska", abbr: "NE" },
  sidney_ne: { name: "Sidney", state: "Nebraska", abbr: "NE" },
  valentine: { name: "Valentine", state: "Nebraska", abbr: "NE" },
  // Nevada
  carson_city: { name: "Carson City", state: "Nevada", abbr: "NV" },
  elko: { name: "Elko", state: "Nevada", abbr: "NV" },
  ely: { name: "Ely", state: "Nevada", abbr: "NV" },
  jackpot: { name: "Jackpot", state: "Nevada", abbr: "NV" },
  las_vegas: { name: "Las Vegas", state: "Nevada", abbr: "NV" },
  pioche: { name: "Pioche", state: "Nevada", abbr: "NV" },
  primm: { name: "Primm", state: "Nevada", abbr: "NV" },
  reno: { name: "Reno", state: "Nevada", abbr: "NV" },
  tonopah: { name: "Tonopah", state: "Nevada", abbr: "NV" },
  winnemucca: { name: "Winnemucca", state: "Nevada", abbr: "NV" },
  // New Mexico
  alamogordo: { name: "Alamogordo", state: "New Mexico", abbr: "NM" },
  albuquerque: { name: "Albuquerque", state: "New Mexico", abbr: "NM" },
  artesia: { name: "Artesia", state: "New Mexico", abbr: "NM" },
  carlsbad: { name: "Carlsbad", state: "New Mexico", abbr: "NM" },
  clovis: { name: "Clovis", state: "New Mexico", abbr: "NM" },
  farmington: { name: "Farmington", state: "New Mexico", abbr: "NM" },
  gallup: { name: "Gallup", state: "New Mexico", abbr: "NM" },
  hobbs: { name: "Hobbs", state: "New Mexico", abbr: "NM" },
  las_cruces: { name: "Las Cruces", state: "New Mexico", abbr: "NM" },
  raton: { name: "Raton", state: "New Mexico", abbr: "NM" },
  roswell: { name: "Roswell", state: "New Mexico", abbr: "NM" },
  santa_fe: { name: "Santa Fe", state: "New Mexico", abbr: "NM" },
  socorro: { name: "Socorro", state: "New Mexico", abbr: "NM" },
  tucumcari: { name: "Tucumcari", state: "New Mexico", abbr: "NM" },
  // Oklahoma
  ardmore: { name: "Ardmore", state: "Oklahoma", abbr: "OK" },
  clinton: { name: "Clinton", state: "Oklahoma", abbr: "OK" },
  durant: { name: "Durant", state: "Oklahoma", abbr: "OK" },
  enid: { name: "Enid", state: "Oklahoma", abbr: "OK" },
  guymon: { name: "Guymon", state: "Oklahoma", abbr: "OK" },
  idabel: { name: "Idabel", state: "Oklahoma", abbr: "OK" },
  lawton: { name: "Lawton", state: "Oklahoma", abbr: "OK" },
  mcalester: { name: "McAlester", state: "Oklahoma", abbr: "OK" },
  oklahoma_city: { name: "Oklahoma City", state: "Oklahoma", abbr: "OK" },
  tulsa: { name: "Tulsa", state: "Oklahoma", abbr: "OK" },
  woodward: { name: "Woodward", state: "Oklahoma", abbr: "OK" },
  // Oregon
  astoria: { name: "Astoria", state: "Oregon", abbr: "OR" },
  bend: { name: "Bend", state: "Oregon", abbr: "OR" },
  burns: { name: "Burns", state: "Oregon", abbr: "OR" },
  coos_bay: { name: "Coos Bay", state: "Oregon", abbr: "OR" },
  eugene: { name: "Eugene", state: "Oregon", abbr: "OR" },
  klamath_falls: { name: "Klamath Falls", state: "Oregon", abbr: "OR" },
  lakeview: { name: "Lakeview", state: "Oregon", abbr: "OR" },
  medford: { name: "Medford", state: "Oregon", abbr: "OR" },
  newport: { name: "Newport", state: "Oregon", abbr: "OR" },
  ontario: { name: "Ontario", state: "Oregon", abbr: "OR" },
  pendleton: { name: "Pendleton", state: "Oregon", abbr: "OR" },
  portland: { name: "Portland", state: "Oregon", abbr: "OR" },
  salem: { name: "Salem", state: "Oregon", abbr: "OR" },
  the_dalles: { name: "The Dalles", state: "Oregon", abbr: "OR" },
  // Texas
  abilene: { name: "Abilene", state: "Texas", abbr: "TX" },
  abilene_tx: { name: "Abilene", state: "Texas", abbr: "TX" },
  amarillo: { name: "Amarillo", state: "Texas", abbr: "TX" },
  amarillo_tx: { name: "Amarillo", state: "Texas", abbr: "TX" },
  austin: { name: "Austin", state: "Texas", abbr: "TX" },
  beaumont: { name: "Beaumont", state: "Texas", abbr: "TX" },
  brownsville: { name: "Brownsville", state: "Texas", abbr: "TX" },
  corpus_christi: { name: "Corpus Christi", state: "Texas", abbr: "TX" },
  dalhart: { name: "Dalhart", state: "Texas", abbr: "TX" },
  dallas: { name: "Dallas", state: "Texas", abbr: "TX" },
  del_rio: { name: "Del Rio", state: "Texas", abbr: "TX" },
  el_paso: { name: "El Paso", state: "Texas", abbr: "TX" },
  fort_stockton: { name: "Fort Stockton", state: "Texas", abbr: "TX" },
  fort_worth: { name: "Fort Worth", state: "Texas", abbr: "TX" },
  galveston: { name: "Galveston", state: "Texas", abbr: "TX" },
  houston: { name: "Houston", state: "Texas", abbr: "TX" },
  huntsville_tx: { name: "Huntsville", state: "Texas", abbr: "TX" },
  junction_tx: { name: "Junction", state: "Texas", abbr: "TX" },
  laredo: { name: "Laredo", state: "Texas", abbr: "TX" },
  longview_tx: { name: "Longview", state: "Texas", abbr: "TX" },
  lubbock: { name: "Lubbock", state: "Texas", abbr: "TX" },
  lufkin: { name: "Lufkin", state: "Texas", abbr: "TX" },
  mcallen: { name: "McAllen", state: "Texas", abbr: "TX" },
  odessa: { name: "Odessa", state: "Texas", abbr: "TX" },
  san_angelo: { name: "San Angelo", state: "Texas", abbr: "TX" },
  san_antonio: { name: "San Antonio", state: "Texas", abbr: "TX" },
  texarkana_tx: { name: "Texarkana", state: "Texas", abbr: "TX" },
  tyler: { name: "Tyler", state: "Texas", abbr: "TX" },
  van_horn: { name: "Van Horn", state: "Texas", abbr: "TX" },
  victoria: { name: "Victoria", state: "Texas", abbr: "TX" },
  waco: { name: "Waco", state: "Texas", abbr: "TX" },
  wichita_falls: { name: "Wichita Falls", state: "Texas", abbr: "TX" },
  // Utah
  cedar_city: { name: "Cedar City", state: "Utah", abbr: "UT" },
  logan: { name: "Logan", state: "Utah", abbr: "UT" },
  moab: { name: "Moab", state: "Utah", abbr: "UT" },
  ogden: { name: "Ogden", state: "Utah", abbr: "UT" },
  price: { name: "Price", state: "Utah", abbr: "UT" },
  provo: { name: "Provo", state: "Utah", abbr: "UT" },
  salina_ut: { name: "Salina", state: "Utah", abbr: "UT" },
  salt_lake_city: { name: "Salt Lake City", state: "Utah", abbr: "UT" },
  st_george: { name: "St. George", state: "Utah", abbr: "UT" },
  vernal: { name: "Vernal", state: "Utah", abbr: "UT" },
  // Washington
  aberdeen: { name: "Aberdeen", state: "Washington", abbr: "WA" },
  bellingham: { name: "Bellingham", state: "Washington", abbr: "WA" },
  colville: { name: "Colville", state: "Washington", abbr: "WA" },
  ellensburg: { name: "Ellensburg", state: "Washington", abbr: "WA" },
  everett: { name: "Everett", state: "Washington", abbr: "WA" },
  grand_coulee: { name: "Grand Coulee", state: "Washington", abbr: "WA" },
  kennewick: { name: "Kennewick", state: "Washington", abbr: "WA" },
  longview: { name: "Longview", state: "Washington", abbr: "WA" },
  olympia: { name: "Olympia", state: "Washington", abbr: "WA" },
  omak: { name: "Omak", state: "Washington", abbr: "WA" },
  port_angeles: { name: "Port Angeles", state: "Washington", abbr: "WA" },
  seattle: { name: "Seattle", state: "Washington", abbr: "WA" },
  spokane: { name: "Spokane", state: "Washington", abbr: "WA" },
  tacoma: { name: "Tacoma", state: "Washington", abbr: "WA" },
  vancouver_wa: { name: "Vancouver", state: "Washington", abbr: "WA" },
  wenatchee: { name: "Wenatchee", state: "Washington", abbr: "WA" },
  yakima: { name: "Yakima", state: "Washington", abbr: "WA" },
  // Wyoming
  casper: { name: "Casper", state: "Wyoming", abbr: "WY" },
  cheyenne: { name: "Cheyenne", state: "Wyoming", abbr: "WY" },
  cody: { name: "Cody", state: "Wyoming", abbr: "WY" },
  evanston: { name: "Evanston", state: "Wyoming", abbr: "WY" },
  gillette: { name: "Gillette", state: "Wyoming", abbr: "WY" },
  jackson: { name: "Jackson", state: "Wyoming", abbr: "WY" },
  laramie: { name: "Laramie", state: "Wyoming", abbr: "WY" },
  rawlins: { name: "Rawlins", state: "Wyoming", abbr: "WY" },
  riverton: { name: "Riverton", state: "Wyoming", abbr: "WY" },
  rock_springs: { name: "Rock Springs", state: "Wyoming", abbr: "WY" },
  sheridan: { name: "Sheridan", state: "Wyoming", abbr: "WY" },
};

/**
 * SCS stores city names as `scs_token` values — packed 64-bit tokens that hold
 * at most 12 base-37 chars, so any city ID longer than 12 chars (e.g.
 * `san_francisco` → `san_francisc`, `coeur_d_alene` → `coeur_d_alen`) gets
 * truncated in `garage.<id>`. Reverse-map every long key to its 12-char form so
 * we can resolve the truncated IDs back to the canonical city.
 */
const TRUNCATED_CITY_INDEX: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const fullKey of Object.keys(ATS_CITIES)) {
    if (fullKey.length > 12) {
      out[fullKey.slice(0, 12)] = fullKey;
    }
  }
  return out;
})();

/** Look up state info for a city. Falls back to title-cased ID for unmapped cities. */
export function getCityInfo(cityId: string): { name: string; state: string; abbr: string } {
  const direct = ATS_CITIES[cityId];
  if (direct) return direct;

  const aliased = TRUNCATED_CITY_INDEX[cityId];
  if (aliased) return ATS_CITIES[aliased];

  return {
    name: cityId.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
    state: "Unknown",
    abbr: "??",
  };
}

/** All unique state abbreviations, sorted. */
export const ATS_STATES = [
  ...new Set(Object.values(ATS_CITIES).map((c) => c.abbr)),
].sort();
