/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavesRouteImport } from './routes/saves'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CloneRouteImport } from './routes/clone'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorSaveIdRouteImport } from './routes/editor.$saveId'
import { Route as EditorSaveIdIndexRouteImport } from './routes/editor.$saveId.index'
import { Route as EditorSaveIdWorldRouteImport } from './routes/editor.$saveId.world'
import { Route as EditorSaveIdTrucksRouteImport } from './routes/editor.$saveId.trucks'
import { Route as EditorSaveIdTrailersRouteImport } from './routes/editor.$saveId.trailers'
import { Route as EditorSaveIdPlayerRouteImport } from './routes/editor.$saveId.player'
import { Route as EditorSaveIdTrucksTruckIdRouteImport } from './routes/editor.$saveId.trucks.$truckId'
import { Route as EditorSaveIdTrailersTrailerIdRouteImport } from './routes/editor.$saveId.trailers.$trailerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesRoute = SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CloneRoute = CloneRouteImport.update({
  id: '/clone',
  path: '/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSaveIdRoute = EditorSaveIdRouteImport.update({
  id: '/editor/$saveId',
  path: '/editor/$saveId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSaveIdIndexRoute = EditorSaveIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorSaveIdRoute,
} as any)
const EditorSaveIdWorldRoute = EditorSaveIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => EditorSaveIdRoute,
} as any)
const EditorSaveIdTrucksRoute = EditorSaveIdTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => EditorSaveIdRoute,
} as any)
const EditorSaveIdTrailersRoute = EditorSaveIdTrailersRouteImport.update({
  id: '/trailers',
  path: '/trailers',
  getParentRoute: () => EditorSaveIdRoute,
} as any)
const EditorSaveIdPlayerRoute = EditorSaveIdPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => EditorSaveIdRoute,
} as any)
const EditorSaveIdTrucksTruckIdRoute =
  EditorSaveIdTrucksTruckIdRouteImport.update({
    id: '/$truckId',
    path: '/$truckId',
    getParentRoute: () => EditorSaveIdTrucksRoute,
  } as any)
const EditorSaveIdTrailersTrailerIdRoute =
  EditorSaveIdTrailersTrailerIdRouteImport.update({
    id: '/$trailerId',
    path: '/$trailerId',
    getParentRoute: () => EditorSaveIdTrailersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/clone': typeof CloneRoute
  '/compare': typeof CompareRoute
  '/mods': typeof ModsRoute
  '/overview': typeof OverviewRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/editor/$saveId': typeof EditorSaveIdRouteWithChildren
  '/editor/$saveId/player': typeof EditorSaveIdPlayerRoute
  '/editor/$saveId/trailers': typeof EditorSaveIdTrailersRouteWithChildren
  '/editor/$saveId/trucks': typeof EditorSaveIdTrucksRouteWithChildren
  '/editor/$saveId/world': typeof EditorSaveIdWorldRoute
  '/editor/$saveId/': typeof EditorSaveIdIndexRoute
  '/editor/$saveId/trailers/$trailerId': typeof EditorSaveIdTrailersTrailerIdRoute
  '/editor/$saveId/trucks/$truckId': typeof EditorSaveIdTrucksTruckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/clone': typeof CloneRoute
  '/compare': typeof CompareRoute
  '/mods': typeof ModsRoute
  '/overview': typeof OverviewRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/editor/$saveId/player': typeof EditorSaveIdPlayerRoute
  '/editor/$saveId/trailers': typeof EditorSaveIdTrailersRouteWithChildren
  '/editor/$saveId/trucks': typeof EditorSaveIdTrucksRouteWithChildren
  '/editor/$saveId/world': typeof EditorSaveIdWorldRoute
  '/editor/$saveId': typeof EditorSaveIdIndexRoute
  '/editor/$saveId/trailers/$trailerId': typeof EditorSaveIdTrailersTrailerIdRoute
  '/editor/$saveId/trucks/$truckId': typeof EditorSaveIdTrucksTruckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/clone': typeof CloneRoute
  '/compare': typeof CompareRoute
  '/mods': typeof ModsRoute
  '/overview': typeof OverviewRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/editor/$saveId': typeof EditorSaveIdRouteWithChildren
  '/editor/$saveId/player': typeof EditorSaveIdPlayerRoute
  '/editor/$saveId/trailers': typeof EditorSaveIdTrailersRouteWithChildren
  '/editor/$saveId/trucks': typeof EditorSaveIdTrucksRouteWithChildren
  '/editor/$saveId/world': typeof EditorSaveIdWorldRoute
  '/editor/$saveId/': typeof EditorSaveIdIndexRoute
  '/editor/$saveId/trailers/$trailerId': typeof EditorSaveIdTrailersTrailerIdRoute
  '/editor/$saveId/trucks/$truckId': typeof EditorSaveIdTrucksTruckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/clone'
    | '/compare'
    | '/mods'
    | '/overview'
    | '/saves'
    | '/settings'
    | '/editor/$saveId'
    | '/editor/$saveId/player'
    | '/editor/$saveId/trailers'
    | '/editor/$saveId/trucks'
    | '/editor/$saveId/world'
    | '/editor/$saveId/'
    | '/editor/$saveId/trailers/$trailerId'
    | '/editor/$saveId/trucks/$truckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/clone'
    | '/compare'
    | '/mods'
    | '/overview'
    | '/saves'
    | '/settings'
    | '/editor/$saveId/player'
    | '/editor/$saveId/trailers'
    | '/editor/$saveId/trucks'
    | '/editor/$saveId/world'
    | '/editor/$saveId'
    | '/editor/$saveId/trailers/$trailerId'
    | '/editor/$saveId/trucks/$truckId'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/clone'
    | '/compare'
    | '/mods'
    | '/overview'
    | '/saves'
    | '/settings'
    | '/editor/$saveId'
    | '/editor/$saveId/player'
    | '/editor/$saveId/trailers'
    | '/editor/$saveId/trucks'
    | '/editor/$saveId/world'
    | '/editor/$saveId/'
    | '/editor/$saveId/trailers/$trailerId'
    | '/editor/$saveId/trucks/$truckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CloneRoute: typeof CloneRoute
  CompareRoute: typeof CompareRoute
  ModsRoute: typeof ModsRoute
  OverviewRoute: typeof OverviewRoute
  SavesRoute: typeof SavesRoute
  SettingsRoute: typeof SettingsRoute
  EditorSaveIdRoute: typeof EditorSaveIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves': {
      id: '/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clone': {
      id: '/clone'
      path: '/clone'
      fullPath: '/clone'
      preLoaderRoute: typeof CloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$saveId': {
      id: '/editor/$saveId'
      path: '/editor/$saveId'
      fullPath: '/editor/$saveId'
      preLoaderRoute: typeof EditorSaveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$saveId/': {
      id: '/editor/$saveId/'
      path: '/'
      fullPath: '/editor/$saveId/'
      preLoaderRoute: typeof EditorSaveIdIndexRouteImport
      parentRoute: typeof EditorSaveIdRoute
    }
    '/editor/$saveId/world': {
      id: '/editor/$saveId/world'
      path: '/world'
      fullPath: '/editor/$saveId/world'
      preLoaderRoute: typeof EditorSaveIdWorldRouteImport
      parentRoute: typeof EditorSaveIdRoute
    }
    '/editor/$saveId/trucks': {
      id: '/editor/$saveId/trucks'
      path: '/trucks'
      fullPath: '/editor/$saveId/trucks'
      preLoaderRoute: typeof EditorSaveIdTrucksRouteImport
      parentRoute: typeof EditorSaveIdRoute
    }
    '/editor/$saveId/trailers': {
      id: '/editor/$saveId/trailers'
      path: '/trailers'
      fullPath: '/editor/$saveId/trailers'
      preLoaderRoute: typeof EditorSaveIdTrailersRouteImport
      parentRoute: typeof EditorSaveIdRoute
    }
    '/editor/$saveId/player': {
      id: '/editor/$saveId/player'
      path: '/player'
      fullPath: '/editor/$saveId/player'
      preLoaderRoute: typeof EditorSaveIdPlayerRouteImport
      parentRoute: typeof EditorSaveIdRoute
    }
    '/editor/$saveId/trucks/$truckId': {
      id: '/editor/$saveId/trucks/$truckId'
      path: '/$truckId'
      fullPath: '/editor/$saveId/trucks/$truckId'
      preLoaderRoute: typeof EditorSaveIdTrucksTruckIdRouteImport
      parentRoute: typeof EditorSaveIdTrucksRoute
    }
    '/editor/$saveId/trailers/$trailerId': {
      id: '/editor/$saveId/trailers/$trailerId'
      path: '/$trailerId'
      fullPath: '/editor/$saveId/trailers/$trailerId'
      preLoaderRoute: typeof EditorSaveIdTrailersTrailerIdRouteImport
      parentRoute: typeof EditorSaveIdTrailersRoute
    }
  }
}

interface EditorSaveIdTrailersRouteChildren {
  EditorSaveIdTrailersTrailerIdRoute: typeof EditorSaveIdTrailersTrailerIdRoute
}

const EditorSaveIdTrailersRouteChildren: EditorSaveIdTrailersRouteChildren = {
  EditorSaveIdTrailersTrailerIdRoute: EditorSaveIdTrailersTrailerIdRoute,
}

const EditorSaveIdTrailersRouteWithChildren =
  EditorSaveIdTrailersRoute._addFileChildren(EditorSaveIdTrailersRouteChildren)

interface EditorSaveIdTrucksRouteChildren {
  EditorSaveIdTrucksTruckIdRoute: typeof EditorSaveIdTrucksTruckIdRoute
}

const EditorSaveIdTrucksRouteChildren: EditorSaveIdTrucksRouteChildren = {
  EditorSaveIdTrucksTruckIdRoute: EditorSaveIdTrucksTruckIdRoute,
}

const EditorSaveIdTrucksRouteWithChildren =
  EditorSaveIdTrucksRoute._addFileChildren(EditorSaveIdTrucksRouteChildren)

interface EditorSaveIdRouteChildren {
  EditorSaveIdPlayerRoute: typeof EditorSaveIdPlayerRoute
  EditorSaveIdTrailersRoute: typeof EditorSaveIdTrailersRouteWithChildren
  EditorSaveIdTrucksRoute: typeof EditorSaveIdTrucksRouteWithChildren
  EditorSaveIdWorldRoute: typeof EditorSaveIdWorldRoute
  EditorSaveIdIndexRoute: typeof EditorSaveIdIndexRoute
}

const EditorSaveIdRouteChildren: EditorSaveIdRouteChildren = {
  EditorSaveIdPlayerRoute: EditorSaveIdPlayerRoute,
  EditorSaveIdTrailersRoute: EditorSaveIdTrailersRouteWithChildren,
  EditorSaveIdTrucksRoute: EditorSaveIdTrucksRouteWithChildren,
  EditorSaveIdWorldRoute: EditorSaveIdWorldRoute,
  EditorSaveIdIndexRoute: EditorSaveIdIndexRoute,
}

const EditorSaveIdRouteWithChildren = EditorSaveIdRoute._addFileChildren(
  EditorSaveIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CloneRoute: CloneRoute,
  CompareRoute: CompareRoute,
  ModsRoute: ModsRoute,
  OverviewRoute: OverviewRoute,
  SavesRoute: SavesRoute,
  SettingsRoute: SettingsRoute,
  EditorSaveIdRoute: EditorSaveIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
